name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main
env:
  VITE_FIREBASE_APIKEY: ${{ secrets.VITE_FIREBASE_APIKEY }}
  VITE_FIREBASE_APPID: ${{ secrets.VITE_FIREBASE_APPID }}
  VITE_FIREBASE_AUTHDOMAIN: ${{ secrets.VITE_FIREBASE_AUTHDOMAIN }}
  VITE_FIREBASE_DATABASEURL: ${{ secrets.VITE_FIREBASE_DATABASEURL }}
  VITE_FIREBASE_PROJECTID: ${{ secrets.VITE_FIREBASE_PROJECTID }} 
  VITE_FIREBASE_MEASUREMENTID: ${{ secrets.VITE_FIREBASE_MEASUREMENTID }}
  VITE_FIREBASE_MESSAGINGSENDERID: ${{ vars.VITE_FIREBASE_MESSAGINGSENDERID }}
  VITE_FIREBASE_STORAGEBUCKET: ${{ secrets.VITE_FIREBASE_STORAGEBUCKET }}
  VITE_OPENAI_API_KEY: ${{ secrets.VITE_OPENAI_API_KEY }}
  VITE_ADMIN_UID: ${{ secrets.VITE_ADMIN_UID }}
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CONFESS_ME_DEEDE }}'
          channelId: live
          projectId: confess-me-deede
